from __future__ import annotations

import json
import re
from html import escape
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

JSON = Dict[str, Any]


class ProjectScaffolder:
    TEMPLATE_VALUES = {"cities2-csharp", "cities2-ui", "cities2-hybrid"}
    MODE_VALUES = {"create", "replace", "upsert"}

    def __init__(
        self,
        workspace: Path,
        templates_dir: Optional[Path] = None,
        additional_workspaces: Optional[Sequence[Path]] = None,
    ) -> None:
        self.workspace = workspace.resolve()
        self.allowed_workspaces = self._build_allowed_workspaces(additional_workspaces or [])
        self.projects_root = self.workspace / "mods"
        self.projects_root.mkdir(parents=True, exist_ok=True)
        self.templates_dir = (templates_dir or (Path(__file__).resolve().parent / "templates")).resolve()

    def _build_allowed_workspaces(self, additional_workspaces: Sequence[Path]) -> List[Path]:
        workspaces: List[Path] = []
        for workspace in [self.workspace, *additional_workspaces]:
            resolved = Path(workspace).resolve()
            if resolved not in workspaces:
                workspaces.append(resolved)
        return workspaces

    def _is_within_allowed_workspace(self, path: Path) -> bool:
        return any(workspace == path or workspace in path.parents for workspace in self.allowed_workspaces)

    def resolve_workspace_path(self, rel_or_abs: str) -> Path:
        p = Path(rel_or_abs)
        if not p.is_absolute():
            p = self.workspace / p
        rp = p.resolve()
        if not self._is_within_allowed_workspace(rp):
            allowed = ", ".join(str(workspace) for workspace in self.allowed_workspaces)
            raise ValueError(f"Path must stay inside configured workspaces: {allowed}")
        return rp

    @staticmethod
    def slug(name: str) -> str:
        s = re.sub(r"[^a-zA-Z0-9]+", "-", name.strip().lower())
        return re.sub(r"-+", "-", s).strip("-") or "cities2-mod"

    @staticmethod
    def to_namespace(slug: str) -> str:
        parts = [p for p in re.split(r"[^a-zA-Z0-9]+", slug) if p]
        if not parts:
            return "Cities2Mod"
        return "".join(p[:1].upper() + p[1:] for p in parts)

    @staticmethod
    def _default_metadata(name: str, slug: str) -> JSON:
        return {
            "mod_id": "",
            "display_name": name,
            "short_description": f"{name} generated by Cities2-MCP modding tools.",
            "game_version": "1.3.*",
            "github_url": "",
            "forum_url": "",
            "version": "0.1.0",
            "project_slug": slug,
            "root_namespace": ProjectScaffolder.to_namespace(slug),
        }

    @staticmethod
    def _merge_defaults(defaults: JSON, value: Optional[JSON]) -> JSON:
        out = dict(defaults)
        if value:
            for k, v in value.items():
                out[str(k)] = v
        return out

    @staticmethod
    def _default_options(template: str) -> JSON:
        include_ui_pipeline = "auto"
        if template == "cities2-csharp":
            include_ui_pipeline = False
        elif template in {"cities2-ui", "cities2-hybrid"}:
            include_ui_pipeline = True
        return {
            "include_settings": True,
            "include_localization": True,
            "include_harmony": True,
            "include_ui_pipeline": include_ui_pipeline,
            "include_changelog": True,
        }

    @staticmethod
    def _bool_option(opts: JSON, key: str, default: bool) -> bool:
        value = opts.get(key, default)
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            lowered = value.strip().lower()
            if lowered in {"1", "true", "yes", "on"}:
                return True
            if lowered in {"0", "false", "no", "off"}:
                return False
        return default

    @staticmethod
    def _xml_node(tag: str, value: str) -> str:
        if not value:
            return ""
        return f"    <{tag}>{escape(value)}</{tag}>\n"

    def _template_tokens(self, template: str, metadata: JSON, options: JSON) -> JSON:
        include_harmony = self._bool_option(options, "include_harmony", True)
        include_settings = self._bool_option(options, "include_settings", True)
        include_localization = self._bool_option(options, "include_localization", True)
        root_namespace = str(metadata.get("root_namespace", "Cities2Mod"))

        using_harmony = "using HarmonyLib;\n" if include_harmony else ""
        harmony_field = "    private Harmony? _harmony;\n" if include_harmony else ""
        setting_field = "    public static Setting? CurrentSetting;\n" if include_settings else ""

        onload_settings = ""
        ondispose_settings = ""
        onload_localization = ""
        if include_settings:
            onload_settings = (
                "        CurrentSetting = new Setting(this);\n"
                "        CurrentSetting.RegisterInOptionsUI();\n"
                f"        AssetDatabase.global.LoadSettings(nameof({root_namespace}), CurrentSetting, new Setting(this));\n\n"
            )
            ondispose_settings = (
                "        if (CurrentSetting != null)\n"
                "        {\n"
                "            CurrentSetting.UnregisterInOptionsUI();\n"
                "            CurrentSetting = null;\n"
                "        }\n"
            )
            if include_localization:
                onload_localization = (
                    '        GameManager.instance.localizationManager.AddSource("en-US", new LocaleEN(CurrentSetting));\n\n'
                )

        onload_harmony = ""
        ondispose_harmony = ""
        harmony_package_reference = ""
        if include_harmony:
            onload_harmony = (
                f'        _harmony = new Harmony("{root_namespace}.patches");\n'
                "        _harmony.PatchAll(typeof(Mod).Assembly);\n"
            )
            ondispose_harmony = f'        _harmony?.UnpatchAll("{root_namespace}.patches");\n        _harmony = null;\n'
            harmony_package_reference = (
                "  <ItemGroup>\n"
                '    <PackageReference Include="Lib.Harmony" Version="2.2.2" />\n'
                "  </ItemGroup>\n\n"
            )

        include_ui_pipeline_raw = options.get("include_ui_pipeline", "auto")
        include_ui_pipeline = include_ui_pipeline_raw
        if include_ui_pipeline_raw == "auto":
            include_ui_pipeline = template in {"cities2-ui", "cities2-hybrid"}
        if not isinstance(include_ui_pipeline, bool):
            include_ui_pipeline = template in {"cities2-ui", "cities2-hybrid"}

        ui_build_target = ""
        if include_ui_pipeline:
            ui_build_target = (
                "  <Target Name=\"BuildUI\" BeforeTargets=\"AfterBuild\">\n"
                '    <Exec Command="npm install" WorkingDirectory="$(ProjectDir)ui" />\n'
                '    <Exec Command="npm run build" WorkingDirectory="$(ProjectDir)ui" />\n'
                "  </Target>\n\n"
                "  <Target Name=\"CopyUIFiles\" AfterTargets=\"DeployWIP\">\n"
                "    <ItemGroup>\n"
                "      <UIFiles Include=\"ui\\dist\\**\\*.*\" />\n"
                "    </ItemGroup>\n"
                "    <Copy SourceFiles=\"@(UIFiles)\" DestinationFiles=\"@(UIFiles->'$(DeployDir)\\UI\\%(RecursiveDir)%(Filename)%(Extension)')\" />\n"
                "  </Target>\n"
            )

        return {
            "MOD_NAME": str(metadata.get("display_name", "")),
            "DISPLAY_NAME": str(metadata.get("display_name", "")),
            "PROJECT_SLUG": str(metadata.get("project_slug", "")),
            "ROOT_NAMESPACE": str(metadata.get("root_namespace", "")),
            "SHORT_DESCRIPTION": str(metadata.get("short_description", "")),
            "GAME_VERSION": str(metadata.get("game_version", "")),
            "VERSION": str(metadata.get("version", "0.1.0")),
            "USING_HARMONY": using_harmony,
            "HARMONY_FIELD": harmony_field,
            "SETTING_FIELD": setting_field,
            "ONLOAD_SETTINGS": onload_settings,
            "ONLOAD_LOCALIZATION": onload_localization,
            "ONLOAD_HARMONY": onload_harmony,
            "ONDISPOSE_SETTINGS": ondispose_settings,
            "ONDISPOSE_HARMONY": ondispose_harmony,
            "HARMONY_PACKAGE_REFERENCE": harmony_package_reference,
            "MOD_ID_NODE": self._xml_node("ModId", str(metadata.get("mod_id", ""))),
            "GITHUB_NODE": self._xml_node("GitHubLink", str(metadata.get("github_url", ""))),
            "FORUM_NODE": self._xml_node("ForumLink", str(metadata.get("forum_url", ""))),
            "UI_BUILD_TARGET": ui_build_target,
        }

    @staticmethod
    def _render_text(text: str, tokens: JSON) -> str:
        rendered = text
        for k, v in tokens.items():
            rendered = rendered.replace("{{" + str(k) + "}}", str(v))
        rendered = re.sub(r"\{\{[A-Z0-9_]+\}\}", "", rendered)
        return rendered

    @staticmethod
    def _is_text_file(path: Path) -> bool:
        if path.suffix.lower() in {
            ".cs",
            ".csproj",
            ".json",
            ".md",
            ".xml",
            ".txt",
            ".yml",
            ".yaml",
            ".ts",
            ".tsx",
            ".js",
            ".jsx",
            ".css",
            ".gitignore",
        }:
            return True
        return False

    def _copy_template_tree(self, template_dir: Path, target_dir: Path, tokens: JSON) -> List[str]:
        created: List[str] = []
        for src in sorted(template_dir.rglob("*")):
            rel = src.relative_to(template_dir)
            rel_str = str(rel).replace("__PROJECT_SLUG__", str(tokens["PROJECT_SLUG"]))
            dest = target_dir / rel_str
            if src.is_dir():
                dest.mkdir(parents=True, exist_ok=True)
                continue

            dest.parent.mkdir(parents=True, exist_ok=True)
            if self._is_text_file(src):
                content = src.read_text(encoding="utf-8")
                rendered = self._render_text(content, tokens)
                dest.write_text(rendered, encoding="utf-8")
            else:
                dest.write_bytes(src.read_bytes())
            created.append(str(dest))
        return created

    def scaffold_project(
        self,
        name: str,
        template: str,
        target_dir: Optional[str],
        metadata: Optional[JSON],
        options: Optional[JSON],
    ) -> JSON:
        if not str(name).strip():
            raise ValueError("name must be a non-empty string")
        if template not in self.TEMPLATE_VALUES:
            raise ValueError("template must be one of: cities2-csharp, cities2-ui, cities2-hybrid")

        slug = self.slug(name)
        root = self.resolve_workspace_path(target_dir) if target_dir else (self.projects_root / slug)
        template_dir = (self.templates_dir / template).resolve()
        if not template_dir.exists():
            raise FileNotFoundError(f"Missing template directory: {template_dir}")

        if root.exists() and any(root.iterdir()):
            raise ValueError(f"Target directory is not empty: {root}")
        root.mkdir(parents=True, exist_ok=True)

        md = self._merge_defaults(self._default_metadata(name, slug), metadata)
        opts = self._merge_defaults(self._default_options(template), options)
        tokens = self._template_tokens(template, md, opts)

        created = self._copy_template_tree(template_dir, root, tokens)
        warnings: List[str] = []

        include_changelog = self._bool_option(opts, "include_changelog", True)
        if not include_changelog:
            changelog = root / "CHANGELOG.md"
            if changelog.exists():
                changelog.unlink()

        include_settings = self._bool_option(opts, "include_settings", True)
        include_localization = self._bool_option(opts, "include_localization", True)
        if not include_settings:
            for p in [root / "Setting.cs", root / "LocaleEN.cs"]:
                if p.exists():
                    p.unlink()
            if include_localization:
                warnings.append("include_localization=true ignored because include_settings=false")
        elif not include_localization:
            locale_path = root / "LocaleEN.cs"
            if locale_path.exists():
                locale_path.unlink()

        include_ui_pipeline = opts.get("include_ui_pipeline", "auto")
        if template == "cities2-hybrid" and include_ui_pipeline is False:
            warnings.append("Hybrid template keeps UI folder; UI build target removed from csproj when include_ui_pipeline=false")

        created = [path for path in created if Path(path).exists()]

        recommended = []
        if template in {"cities2-ui", "cities2-hybrid"}:
            recommended.append("npm install")
            recommended.append("npm run build")
        if template in {"cities2-csharp", "cities2-hybrid"}:
            recommended.append("dotnet build -c Release")

        return {
            "ok": True,
            "name": name,
            "template": template,
            "project_slug": slug,
            "project_dir": str(root),
            "files_created": created,
            "warnings": warnings,
            "recommended_commands": recommended,
            "metadata": md,
            "options": opts,
        }

    def write_project_file(self, project_dir: str, relative_path: str, content: str, mode: str = "upsert") -> JSON:
        if mode not in self.MODE_VALUES:
            raise ValueError("mode must be one of: create, replace, upsert")

        root = self.resolve_workspace_path(project_dir)
        target = (root / relative_path).resolve()
        if root not in target.parents and target != root:
            raise ValueError("relative_path escapes project dir")

        if mode == "create" and target.exists():
            return {"ok": False, "message": "File already exists", "path": str(target), "mode_applied": mode}
        if mode == "replace" and not target.exists():
            return {"ok": False, "message": "File not found", "path": str(target), "mode_applied": mode}

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return {
            "ok": True,
            "path": str(target),
            "bytes": len(content.encode("utf-8")),
            "mode_applied": mode,
        }

    def list_project_tree(
        self,
        project_dir: str,
        glob: str = "**/*",
        include_hidden: bool = False,
        max_files: int = 2000,
    ) -> JSON:
        root = self.resolve_workspace_path(project_dir)
        max_files = max(1, min(10000, int(max_files)))

        files: List[JSON] = []
        for p in sorted(root.glob(glob)):
            if not p.is_file():
                continue
            rel = p.relative_to(root)
            if not include_hidden and any(part.startswith(".") for part in rel.parts):
                continue
            files.append(
                {
                    "path": str(p),
                    "relative": str(rel),
                    "size": p.stat().st_size,
                }
            )
            if len(files) >= max_files:
                break

        return {
            "ok": True,
            "project_dir": str(root),
            "count": len(files),
            "truncated": len(files) >= max_files,
            "files": files,
        }

    def detect_profile(self, project_dir: str) -> str:
        root = self.resolve_workspace_path(project_dir)
        has_csproj = any(root.glob("*.csproj"))
        has_root_package = (root / "package.json").exists()
        has_ui_package = (root / "ui" / "package.json").exists()

        if has_csproj and has_ui_package:
            return "cities2-hybrid"
        if has_csproj:
            return "cities2-csharp"
        if has_root_package:
            return "cities2-ui"
        return "unknown"

    def find_primary_csproj(self, root: Path) -> Optional[Path]:
        csprojs = sorted(root.glob("*.csproj"))
        return csprojs[0] if csprojs else None


def json_dumps_pretty(payload: JSON) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2)
